### PR TITLE
fix affirmation popping up when pressing back

### LINKED ISSUE #326: pressing back on a preview page may show the affirmation popup

### PR DESCRIPTION
**Pull request by aahvocado**
fixes #326

### CODE REVIEW

File: react/client/src/contexts/RoutingContext.tsx [hunk 1]
```diff
@@ -26,50 +36,77 @@ const PreRoutingContextProvider = ({
...
+    if (pageEnum !== PAGES[STEP_ENUMS.NONE] && formSteps.length <= 1) {
       // setCurrentStepIdx(0);
       // setFormSteps([STEP_ENUMS.NONE]);
       // navigateToFormPage(PAGES[STEP_ENUMS.NONE]);
     }
 
-    // when going back to home page, clear out steps
+    if (newPageData.isViewedStep && !newPageData.isCurrentStep) {
+      handleBrowserPageNav(stepEnum);
+    }
```
Comment (aahvocado) [inline react/client/src/contexts/RoutingContext.tsx:91]: This part now fixes the when the user presses Back or Forward on the browser.
