### PR TITLE
1172 fix faq alignment

### LINKED ISSUE #1172: Fix content misalignment on FAQ page
### Overview
The alignment on the FAQ page does not match the wireframes. The content on the page isn't aligned to the header and footer logo and the banner header and paragraph text have a different padding. 

##### Example
Section 1

### Action Items
- [x] Fix alignment of the content on the page - everything should line up with header/footer
- [x] Fix padding - around the title/image

### Resources/Notes
Design can be found [here ](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=14813-38617&mode=design&t=tYR9cXLGqdCAUqKq-4)

If needed, the Design team uses this current [grid system and breakpoints](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=14813-39554&mode=design&t=tYR9cXLGqdCAUqKq-4)

### PR DESCRIPTION
**Pull request by davidwiese**
Fixes #1172 

### Changes made

- Adjusted `AppFooter` to exactly match and align with `AppHeader` - otherwise none of the content would be aligned with both
- Adjusted `FAQHeader` content width to stay aligned with the `AppHeader` and `AppFooter`
- Adjusted `FAQHeader` text and image to have correct line numbers and spacing
- Adjusted `FAQContainer` content width to stay aligned with the `AppHeader` and `AppFooter`

### Reason for changes

- Implementation of the FAQ page did not match design team's wireframes. It has a more polished/professional look and feel now

### CODE REVIEW

File: products/statement-generator/src/components-layout/AppFooter.tsx [hunk 1]
```diff
@@ -48,6 +53,7 @@ const useStyles = makeStyles(({ breakpoints, palette, spacing }) =>
 
       [breakpoints.down(breakpoints.values.md)]: {
         flexDirection: 'column',
+        marginLeft: '-8px',
```
Comment (sydneywalcoff) [inline products/statement-generator/src/components-layout/AppFooter.tsx:56]: here as well, please

**Review by sydneywalcoff — CHANGES_REQUESTED** [review]
Hey @davidwiese! This looks really good. I left one request, but it's pretty small.

File: products/statement-generator/src/components-layout/AppFooter.tsx [hunk 2]
```diff
@@ -39,6 +39,11 @@ const useStyles = makeStyles(({ breakpoints, palette, spacing }) =>
       display: 'flex',
       flexDirection: 'column',
       padding: spacing(1),
+      marginLeft: '-16px',
+
+      [breakpoints.down(breakpoints.values.md)]: {
+        marginLeft: '-8px',
+      },
```
Comment (sydneywalcoff) [inline products/statement-generator/src/components-layout/AppFooter.tsx:46]: Because the weird footer alignment is caused by padding, best practice would say to adjust the padding before implementing a negative margin.

**Comment by davidwiese** [comment]
> Hey @davidwiese! This looks really good. I left one request, but it's pretty small.

@sydneywalcoff Made adjustments to get everything lined up at all breakpoints without negative margins

**Review by sydneywalcoff — APPROVED** [review]
@davidwiese looks great! Thank you for making those changes!!
